name: Deploy Supabase Functions

on:
  push:
    branches:
      - main   # or whichever branch you deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Supabase CLI
        run: npm install -g supabase

      - name: Deploy instagram-scraper function
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          supabase link --project-ref annjzekiqvbupmqwldiy
          supabase functions deploy instagram-scraper
